### ISSUE TITLE
installation fails on Debian 12 KDE/X

### ISSUE THREAD

**Issue by thombook** [RedBearAK/toshy#125]
trying to install toshy on a Debian 12 KDE/X session fails with:

`Collecting pywayland
  Using cached pywayland-0.4.17.tar.gz (219 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-70apjavr/pywayland.egg-info
      writing /tmp/pip-modern-metadata-70apjavr/pywayland.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-70apjavr/pywayland.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-modern-metadata-70apjavr/pywayland.egg-info/entry_points.txt
      writing requirements to /tmp/pip-modern-metadata-70apjavr/pywayland.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-70apjavr/pywayland.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-70apjavr/pywayland.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-70apjavr/pywayland.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-70apjavr/pywayland.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-70apjavr/pywayland-0.4.17.dist-info'
      Traceback (most recent call last):
        File "/home/ox/.config/toshy/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ox/.config/toshy/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ox/.config/toshy/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 175, in <module>
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/command/dist_info.py", line 96, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/tmp/pip-build-env-ptj9sjsf/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 78, in finalize_options
      AssertionError: Specified Wayland protocol file, /usr/share/wayland/wayland.xml, does not exist please specify valid protocol file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error installing/upgrading Python packages. Installer exiting.
`

**Comment by RedBearAK** [comment]
@thombook 

Can you try this and then run the Toshy install again?

`sudo apt install wayland-dev`

This may not be the right package name. The problem just seems to be this: 

> AssertionError: Specified Wayland protocol file, /usr/share/wayland/wayland.xml, does not exist

Installing “wayland-devel” on Fedora Asahi Remix took care of something similar.

**Comment by thombook** [comment]
thanks for the hint, it is libwayland-dev on Debian. works now.

**Comment by RedBearAK** [comment]
@thombook 

Thanks for the report. I'll do some testing and fix the package list for Debian. I'll have to take a look at Ubuntu as well.

**Comment by RedBearAK** [comment]
Were you on some sort of minimal install of Debian 12? I'm not observing the same problem with Debian 12 test VM.

**Comment by thombook** [comment]
not that I am aware of. However I have to say that I used the DVD install for arm64 inside a VMware Fusion VM - maybe the package selections are a bit different from other Archs here...

**Comment by RedBearAK** [comment]
That's funny, Fedora Asahi Remix is dedicated to the Apple Silicon ARM machines and had the same issue. Maybe that's the commonality, for some reason they are leaving out a package that has that Wayland XML file in it. 

It may be redundant for the X86 arch but it shouldn't hurt to add the package to the list. 

Thanks again. Will close this out once I get the package lists updated.

**Comment by RedBearAK** [comment]
OK, that should take care of it. I also added the app class for the Firefox ESR that Debian 12 uses. You'll get that update to the config if you download a new zip and reinstall. 

It should work now even if you uninstall `libwayland-dev` prior to running the installer. If you're feeling adventuresome.
