### ISSUE TITLE
(Question) Failed to install on Bazzite OS

### ISSUE THREAD

**Issue by jarjut** [RedBearAK/toshy#431]
I try run the setup with `./setup_toshy.py install --override-distro silverblue` because bazzite is based on silverblue. This the toshy installer sees 

> (EV) Toshy installer sees this environment:
	 DISTRO_ID        = 'silverblue'
	 DISTRO_VER       = '41'
	 VARIANT_ID       = 'bazzite-deck'
	 SESSION_TYPE     = 'wayland'
	 DESKTOP_ENV      = 'kde'
	 DE_MAJ_VER       = '6'
	 WINDOW_MGR       = 'kwin_wayland'

And then the installer shows error in installing/upgrading python packages

```bash
Collecting pywayland
  Using cached pywayland-0.4.18.tar.gz (247 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info
      writing /tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info/entry_points.txt
      writing requirements to /tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-8rvj3kbk/pywayland.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-8rvj3kbk/pywayland-0.4.18.dist-info'
      Traceback (most recent call last):
        File "/home/jarjut/.config/toshy/.venv/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/jarjut/.config/toshy/.venv/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jarjut/.config/toshy/.venv/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 376, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 175, in <module>
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/command/dist_info.py", line 98, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command
          cmd_obj.ensure_finalized()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-x301cqdf/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "<string>", line 78, in finalize_options
      AssertionError: Specified Wayland protocol file, /usr/share/wayland/wayland.xml, does not exist please specify valid protocol file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

```

**Comment by RedBearAK** [comment]
@jarjut 

Find this in “setup_toshy.py”: 

https://github.com/RedBearAK/toshy/blob/5bd8ef9c48375e408e9db53e77d18c2c380fde89/setup_toshy.py#L710

Add the “wayland-devel” package to the list, like in the “fedora-based” package list. That should fix this. 

Don’t close the issue even if it works. I need to update the install script when I get home in a few days.

**Comment by jarjut** [comment]
can confirm it works after adding that package. thanks

**Comment by RedBearAK** [comment]
@jarjut 

Thanks for the confirmation. I guess this means you’re the first to try it on Bazzite, where that package is not pre-installed the way it apparently was on Silverblue and Kinoite. 

Can you show what `toshy-env` sees as the distro ID now that it’s installed? Without the override you used with the installer script. Some of the immutable variants do actually set a custom distro ID. I should add “bazzite” to the distro list if it would be valid.

**Comment by jarjut** [comment]
> (EV) Toshy env_info module sees this environment:
		 DISTRO_ID       = 'bazzite'
		 DISTRO_VER      = '41'
		 VARIANT_ID      = 'bazzite-deck'
		 SESSION_TYPE    = 'wayland'
		 DESKTOP_ENV     = 'kde'
		 DE_MAJ_VER      = '6'
		 WINDOW_MGR      = 'kwin_wayland'

**Comment by RedBearAK** [comment]
@jarjut 

Thanks, that’s very helpful.

**Comment by RedBearAK** [comment]
@jarjut 

Using your feedback, I updated the installer script with the "bazzite" distro ID, and the "wayland-devel" package for the Fedora immutables. Those using Bazzite should have an easier time installing Toshy without issues. Thanks!

**Comment by slagathor69** [comment]
Even using latest version by pulling repository or manually editing file to have wayland-devel, I still get an error with pywayland that prevents it from completing. I believe it's because this is an immutable distro and it's trying to find the /usr/share/wayland.xml file which doesn't exist in /usr/share and is actually in /var as shown below

***Note:***
*I've tried using bazzite, silverblue, fedora, and solus for distoid. silverblue and bazzite are the only ones that get far enough to get this error.*

## Locating the wayland.xml file
```
slagathor@bazzite:~/Downloads/toshy$ sudo find / -name "wayland.xml"
find: ‘/proc/17972/task/17972/net’: Invalid argument
find: ‘/proc/17972/net’: Invalid argument
find: ‘/proc/67277’: No such file or directory
find: ‘/run/user/1000/doc’: Permission denied
find: File system loop detected; ‘/sysroot/ostree/deploy/default/deploy/0e65d40a4f269b23b261b7a3bba61e563734f7816e3c1675a4320216d056f454.0’ is part of the same file system loop as ‘/’.
/sysroot/ostree/deploy/default/deploy/5e367e87152787747a055b35a3c57810901a80fafdc687d54871943c4cee2535.0/usr/share/wayland/wayland.xml
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/23.08/0a3508e2e09c748e207965e0c0e25a52e6ae77716230be986cbbfb4b29295eb5/files/share/wayland/wayland.xml
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/24.08/4032cef5b0b698b46df684fc68527252cb7350f39bd90b25bb0c79766911de23/files/share/wayland/wayland.xml
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/47/f0e4bfebfb877c9606f0e0eb57b59aed2ccbe7a0d7de04a4c2328e31868a1cce/files/share/wayland/wayland.xml
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.7/2404795557d1df2add27652dc45f57a63dd6beeb7ecc25677c29ee3b8b3cc8cc/files/share/wayland/wayland.xml
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.8/2d9009618be16eaf5e536f1ba42be7ff471eab526da8d1a1ee0d1ffcd3bd6a0a/files/share/wayland/wayland.xml
```



## Error during Installation attempt
```
slagathor@bazzite:~/Downloads/toshy$ ./setup_toshy.py install --override-distro bazzite


(!!) NOTICE: It is ESSENTIAL to have your system completely updated.

Have you updated your system recently? [y/N]: y

§  Getting environment information...
================================================================================
The active init system is: 'systemd' (Systemd)

(EV) Toshy installer sees this environment:
	 DISTRO_ID        = 'bazzite'
	 DISTRO_VER       = '41'
	 VARIANT_ID       = 'bazzite-nvidia-open'
	 SESSION_TYPE     = 'wayland'
	 DESKTOP_ENV      = 'kde'
	 DE_MAJ_VER       = '6'
	 WINDOW_MGR       = 'kwin_wayland'

Is user "slagathor" an admin user that can run "sudo" commands? [y/n]: y

  ----------------------------------------  
  -- SUDO PASSWORD REQUIRED TO CONTINUE --  
  ----------------------------------------  

[sudo] password for slagathor:

Using elevated privileges...


§  Installing native packages for this distro type...
================================================================================
Distro is Fedora-type immutable. Using "rpm-ostree" instead of DNF.
Package 'cairo-devel' is already installed. Skipping.
Package 'cairo-gobject-devel' is already installed. Skipping.
Package 'dbus-daemon' is already installed. Skipping.
Package 'dbus-devel' is already installed. Skipping.
Package 'evtest' is already installed. Skipping.
Package 'gcc' is already installed. Skipping.
Package 'git' is already installed. Skipping.
Package 'gobject-introspection-devel' is already installed. Skipping.
Package 'libappindicator-gtk3' is already installed. Skipping.
Package 'libnotify' is already installed. Skipping.
Package 'libxkbcommon-devel' is already installed. Skipping.
Package 'python3-dbus' is already installed. Skipping.
Package 'python3-devel' is already installed. Skipping.
Package 'python3-pip' is already installed. Skipping.
Package 'python3-tkinter' is already installed. Skipping.
Package 'systemd-devel' is already installed. Skipping.
Package 'xset' is already installed. Skipping.
Package 'zenity' is already installed. Skipping.
Checking out tree 2cb1e18... done
Enabled rpm-md repositories: copr:copr.fedorainfracloud.org:ilyaz:LACT copr:copr.fedorainfracloud.org:matte-schwartz:sunshine copr:copr.fedorainfracloud.org:rodoma92:kde-cdemu-manager copr:copr.fedorainfracloud.org:rodoma92:rmlint copr:copr.fedorainfracloud.org:rok:cdemu updates fedora copr:copr.fedorainfracloud.org:codifryed:CoolerControl updates-archive
Importing rpm-md... done
rpm-md repo 'copr:copr.fedorainfracloud.org:ilyaz:LACT' (cached); generated: 2024-11-14T20:15:31Z solvables: 40
rpm-md repo 'copr:copr.fedorainfracloud.org:matte-schwartz:sunshine' (cached); generated: 2024-08-12T15:47:19Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:rodoma92:kde-cdemu-manager' (cached); generated: 2024-10-29T12:13:12Z solvables: 16
rpm-md repo 'copr:copr.fedorainfracloud.org:rodoma92:rmlint' (cached); generated: 2024-10-29T12:31:09Z solvables: 4
rpm-md repo 'copr:copr.fedorainfracloud.org:rok:cdemu' (cached); generated: 2024-10-21T13:15:21Z solvables: 23
rpm-md repo 'updates' (cached); generated: 2024-11-27T02:15:18Z solvables: 11010
rpm-md repo 'fedora' (cached); generated: 2024-10-24T13:55:59Z solvables: 76624
rpm-md repo 'copr:copr.fedorainfracloud.org:codifryed:CoolerControl' (cached); generated: 2024-11-16T03:39:38Z solvables: 6
rpm-md repo 'updates-archive' (cached); generated: 2024-11-28T03:47:46Z solvables: 11751
Resolving dependencies... done
No change.
All necessary native distro packages are installed.
   >> Task completed successfully <<   


§  Checking status of "uinput" kernel module...
================================================================================
The "uinput" module is not loaded, loading now...
   >> Task completed successfully <<   


§  Installing "udev" rules file for keymapper...
================================================================================
Correct "udev" rules already in place.
   >> Task completed successfully <<   


§  Checking if user is in "input" group...
================================================================================
Group "input" already exists.
User "slagathor" is a member of group "input".
   >> Task completed successfully <<   


§  Cloning keymapper branch...
================================================================================
Cloning branch "main" from https://github.com/RedBearAK/xwaykeyz.git...
Cloning into '/var/home/slagathor/Downloads/toshy/keymapper-temp'...
remote: Enumerating objects: 3010, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 3010 (delta 147), reused 252 (delta 139), pack-reused 2740 (from 1)
Receiving objects: 100% (3010/3010), 675.72 KiB | 3.95 MiB/s, done.
Resolving deltas: 100% (1923/1923), done.
   >> Task completed successfully <<   


§  Backing up existing Toshy config folder...
================================================================================
Prepared existing config file data for merging into new config.
No existing preferences db file found in /home/slagathor/.config/toshy.
Backup completed to '/var/home/slagathor/.config/toshy_config_backups/toshy_20241128_023220'
   >> Task completed successfully <<   


§  Installing Toshy files...
================================================================================
Installed default Toshy config file.
Toshy files installed in '/home/slagathor/.config/toshy'.
Existing user customizations applied to the new config file.
   >> Task completed successfully <<   


§  Setting up the Python virtual environment...
================================================================================
Using Python version 3.13.
Python virtual environment setup complete.
Location: '/home/slagathor/.config/toshy/.venv'
   >> Task completed successfully <<   


§  Installing/upgrading Python packages...
================================================================================
Requirement already satisfied: pip in /home/slagathor/.config/toshy/.venv/lib64/python3.13/site-packages (24.2)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
Successfully installed pip-24.3.1
Collecting wheel
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
Installing collected packages: wheel
Successfully installed wheel-0.45.1
Collecting setuptools
  Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
Successfully installed setuptools-75.6.0
Collecting pillow
  Using cached pillow-11.0.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Using cached pillow-11.0.0-cp313-cp313-manylinux_2_28_x86_64.whl (4.4 MB)
Installing collected packages: pillow
Successfully installed pillow-11.0.0
Collecting lockfile
  Using cached lockfile-0.12.2-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting dbus-python
  Using cached dbus_python-1.3.2-cp313-cp313-linux_x86_64.whl
Collecting systemd-python
  Using cached systemd_python-235-cp313-cp313-linux_x86_64.whl
Collecting pygobject<=3.44.1
  Using cached PyGObject-3.44.1-cp313-cp313-linux_x86_64.whl
Collecting tk
  Using cached tk-0.1.0-py3-none-any.whl.metadata (693 bytes)
Collecting sv_ttk
  Using cached sv_ttk-2.6.0-py3-none-any.whl.metadata (2.5 kB)
Collecting watchdog
  Using cached watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
Collecting psutil
  Using cached psutil-6.1.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Collecting xkbcommon<1.1
  Using cached xkbcommon-1.0.1-cp313-cp313-linux_x86_64.whl
Collecting hyprpy
  Using cached hyprpy-0.1.8-py3-none-any.whl.metadata (3.4 kB)
Collecting i3ipc
  Using cached i3ipc-2.2.1-py3-none-any.whl.metadata (4.7 kB)
Collecting pywayland
  Using cached pywayland-0.4.18.tar.gz (247 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-429f0egj/pywayland.egg-info
      writing /tmp/pip-modern-metadata-429f0egj/pywayland.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-429f0egj/pywayland.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-modern-metadata-429f0egj/pywayland.egg-info/entry_points.txt
      writing requirements to /tmp/pip-modern-metadata-429f0egj/pywayland.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-429f0egj/pywayland.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-429f0egj/pywayland.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-429f0egj/pywayland.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-429f0egj/pywayland.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-429f0egj/pywayland-0.4.18.dist-info'
      Traceback (most recent call last):
        File "/home/slagathor/.config/toshy/.venv/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/slagathor/.config/toshy/.venv/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/slagathor/.config/toshy/.venv/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 175, in <module>
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/command/dist_info.py", line 99, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command
          cmd_obj.ensure_finalized()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-4xgzughy/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "<string>", line 78, in finalize_options
      AssertionError: Specified Wayland protocol file, /usr/share/wayland/wayland.xml, does not exist please specify valid protocol file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(EE) Problem installing/upgrading Python packages. Installer exiting.
```

**Comment by slagathor69** [comment]
I'm sorry I forgot to follow up to this. I ended up deleting Bazzite and just installing Arch due to a couple other things I needed that weren't working with an immutable system so no issues now.

**Comment by domainus** [comment]
Sorry for the necro, but incase any one else is having the same issue, you have to try to install the script once so it will layer on the proper packages, then reboot, and rerun the install script again for it to successfully install.
